[package]
name = "reuseport"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[dependencies]
bytes = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"